### ISSUE TITLE
OpenGL Compilation issue

### ISSUE THREAD

**Issue by milijan** [goffioul/QtHandles#1]
I get the following error when compiling the head:

C:\Octave\QtHandles\src\gl-select.cc:45: error: C2248: 'opengl_renderer::setup_opengl_transformation' : cannot access private member declared in class 'opengl_renderer'

Any idea?

extra notes: I used the 
http://sourceforge.net/projects/octave/files/Octave%20Windows%20binaries/Octave%203.6.2%20for%20Windows%20Microsoft%20Visual%20Studio/

octave-3.6.2-vs2010-setup.exe

Perhaps there is a later version of octave where the method is public??

**Comment by goffioul** [comment]
On Tue, Jan 8, 2013 at 11:54 AM, milijan notifications@github.com wrote:

> I get the following error when compiling the head:
> 
> C:\Octave\QtHandles\src\gl-select.cc:45: error: C2248:
> 'opengl_renderer::setup_opengl_transformation' : cannot access private
> member declared in class 'opengl_renderer'
> 
> Any idea?

What version of octave are you using? QtHandles can only be compiled with
octave development branch.

Michael.

**Comment by goffioul** [comment]
OK, the answer is in your initial mail (for whatever reason, it didn't appear in my mail client). So indeed, the current head of QtHandles cannot be compiled with octave-3.6.2.

**Comment by goffioul** [comment]
For reference, the change was made there:

http://hg.savannah.gnu.org/hgweb/octave/rev/a1e1f914ae79

**Comment by milijan** [comment]
Thanks a lot for the quick response.
